apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticmq-config
  namespace: solidarytech
  labels:
    app.kubernetes.io/part-of: solidarytech
    Project: SolidaryTech
    Environment: secondary
data:
  elasticmq.conf: |
    include classpath("application.conf")

    node-address {
        protocol = http
        host = "*"
        port = 9324
        context-path = ""
    }

    rest-sqs {
        enabled = true
        bind-port = 9324
        bind-hostname = "0.0.0.0"
        sqs-limits = strict
    }

    # Fila usada pelo donation-service para publicar eventos de notificação
    queues {
        solidary-donations {
            defaultVisibilityTimeout = 30 seconds
            delay = 0 seconds
            receiveMessageWait = 0 seconds
        }
    }