apiVersion: v1
kind: Secret
metadata:
  name: ngo-env
  namespace: solidarytech
  labels:
    app.kubernetes.io/part-of: solidarytech
type: Opaque
stringData:
  PORT: "8081"
  DATABASE_URL: "postgres://sol:sol@psql:5432/sol_db"