apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: solidarytech
  labels:
    app.kubernetes.io/part-of: solidarytech
type: Opaque
stringData:
  POSTGRES_USER: sol
  POSTGRES_PASSWORD: sol
  POSTGRES_DB: sol_db