apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: solidarytech
  labels:
    app.kubernetes.io/part-of: solidarytech
    Project: SolidaryTech
    Environment: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi