apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: solidarytech
  labels:
    app.kubernetes.io/part-of: solidarytech
    Project: SolidaryTech
    Environment: dev
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi