apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: donation
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: solidarytech
    Project: SolidaryTech
    Environment: dev
spec:
  image: docker.io/diasdmhub/donation
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: donation
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: solidarytech
    Project: SolidaryTech
    Environment: dev
spec:
  imageRepositoryRef:
    name: donation
  filterTags:
    pattern: '^v[0-9]+\.[0-9]+-(?P<ts>[0-9]{14})-[0-9a-f]{7}$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
