apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: volunteer
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: solidarytech
    Project: SolidaryTech
    Environment: secondary
spec:
  image: docker.io/diasdmhub/volunteer
  interval: 10m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: volunteer
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: solidarytech
    Project: SolidaryTech
    Environment: secondary
spec:
  imageRepositoryRef:
    name: volunteer
  filterTags:
    pattern: '^[0-9]{14}$'
  policy:
    numerical:
      order: asc
