apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: solidarytech
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: solidarytech
    Project: SolidaryTech
    Environment: secondary
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        Atualiza imagens da solidarytech via Flux Image Automation

        {{ range .Changed.Changes }}
        - {{ .OldValue }} -> {{ .NewValue }}
        {{ end }}
    push:
      branch: main
  update:
    path: ./kube
    strategy: Setters
