apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-data
  namespace: observe
  labels:
    app.kubernetes.io/part-of: solidarytech
    Project: SolidaryTech
    Environment: secondary
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
